"""updated user model to use with praetorian

Revision ID: 4cec1edb3b57
Revises: 6a7b317d2ce3
Create Date: 2022-08-05 15:43:07.666500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cec1edb3b57'
down_revision = '6a7b317d2ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable='False')
    op.add_column('user', sa.Column('hashed_password', sa.String(length=60), nullable=False))
    op.add_column('user', sa.Column('roles', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'roles')
    op.drop_column('user', 'hashed_password')
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
