"""change password length

Revision ID: 4eda0132a7cb
Revises: 4cec1edb3b57
Create Date: 2022-08-05 16:19:05.524752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eda0132a7cb'
down_revision = '4cec1edb3b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
