"""length

Revision ID: 69e818700bcd
Revises: 4eda0132a7cb
Create Date: 2022-08-05 16:34:14.689273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e818700bcd'
down_revision = '4eda0132a7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable='False')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
