"""fixed user model relationship

Revision ID: 6a7b317d2ce3
Revises: 26ae2a4be89e
Create Date: 2022-08-05 11:57:20.236112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7b317d2ce3'
down_revision = '26ae2a4be89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'link_image',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
